### ISSUE TITLE
Socketing failes to complete

### ISSUE THREAD

**Issue by BLovegrove** [blaxxun-boop/Jewelcrafting#2] opened 2022-06-12 04:02 UTC
When attempting to socket any piece of gear it always fills up the crafting bar and hangs. 
A mesage saying to upgrade the gear to (insert 1 level higher than current) level appears above the crafting button / bar.

edit: hovering over the craft button shows the tooltip 'missing requirements' but says nothing about what they are and still lets me hit the craft button.

Not sure what other logs I can attach here but hope this helps:

<details>
<summary>

game log

</summary>

```
[Message:   BepInEx] BepInEx 5.4.19.0 - valheim (19/02/2022 9:34:05 p.m.)
[Info   :   BepInEx] Running under Unity v2019.4.31.12409535
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Valheim.ThisGoesHere 2.1.1.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 61 plugins to load
[Info   :   BepInEx] Loading [Craft From Containers 2.2.2]
[Info   :   BepInEx] Loading [Creature Level & Loot Control 4.4.8]
[Info   :   BepInEx] Loading [Spawn That! 1.0.5]
[Info   :   BepInEx] Loading [Custom Raids 1.6.2]
[Info   :Custom Raids] Loading configurations...
[Info   :   BepInEx] Loading [Drop That! 2.3.3]
[Message:Drop That!] Loading general configuration from C:\Users\Brandon\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\config\drop_that.cfg.
[Info   :   BepInEx] Loading [Floors Are Roofs 1.0]
[Info   :   BepInEx] Loading [CameraMod 0.0.8.7]
[Info   :   BepInEx] Loading [RRRCore 0.2.12]
[Info   :   BepInEx] Loading [RRRMonsters 0.2.2]
[Info   :   BepInEx] Loading [RRRNpcs 0.2.3]
[Info   :   BepInEx] Loading [Jotunn 2.6.9]
[Info   :    Jotunn] Initializing LocalizationManager
[Info   :    Jotunn] Initializing CommandManager
[Info   :    Jotunn] Initializing InputManager
[Info   :    Jotunn] Initializing SkillManager
[Info   :    Jotunn] Initializing PrefabManager
[Info   :    Jotunn] Initializing ItemManager
[Info   :    Jotunn] Initializing PieceManager
[Info   :    Jotunn] Initializing CreatureManager
[Info   :    Jotunn] Initializing ZoneManager
[Info   :    Jotunn] Initializing MockManager
[Info   :    Jotunn] Initializing KitbashManager
[Info   :    Jotunn] Initializing GUIManager
[Info   :    Jotunn] Initializing KeyHintManager
[Info   :    Jotunn] Initializing NetworkManager
[Info   :    Jotunn] Initializing SynchronizationManager
[Info   :    Jotunn] Initializing RenderManager
[Info   :    Jotunn] Initializing MinimapManager
[Info   :    Jotunn] Jötunn v2.6.9 loaded successfully
[Info   :   BepInEx] Loading [Use Equipment in Water 0.2.2.0]
[Info   :   BepInEx] Loading [ChickenBoo 2.1.3]
[Info   :   BepInEx] Loading [Crawler 0.0.7]
[Info   :   BepInEx] Loading [Terraheim 2.2.0]
[Info   :Terraheim.Log] Loaded localization for English
[Info   :Terraheim.Log] Status Effects Injected
[Info   :Terraheim.Log] Chaos Armor Found!
[Info   :Terraheim.Log] Judes Equipment Found!
[Info   :Terraheim.Log] Patching complete
[Info   :   BepInEx] Loading [TerraheimItems 2.1.0]
[Info   :TerraheimItems] Loaded localization for English
[Info   :TerraheimItems] Patching complete
[Info   :   BepInEx] Loading [SagesVault 1.1.3]
[Info   :   BepInEx] Loading [BlacksmithTools 2.0.2]
[Info   :   BepInEx] Loading [JudesEquipment 2.2.0]
[Info   :   BepInEx] Loading [Golem 0.0.7]
[Info   :   BepInEx] Loading [DoOrDieMonsters 0.5.3]
[Info   :   BepInEx] Loading [Epic Valheims Additions - by Huntard 1.8.0]
[Info   :EpicValheimsAdditions.Core] Loading...
[Info   :EpicValheimsAdditions.Core] Loaded Prefabs
[Info   :EpicValheimsAdditions.Core] Loaded CraftingPieces
[Info   :EpicValheimsAdditions.Core] Loaded Ingots/scales/ore
[Info   :EpicValheimsAdditions.Core] Loaded MiscItems
[Info   :EpicValheimsAdditions.Core] Loaded BossStuff
[Info   :EpicValheimsAdditions.Core] Loaded HeavymetalWeapons
[Info   :EpicValheimsAdditions.Core] Loaded FrometalWeapons
[Info   :EpicValheimsAdditions.Core] Loaded FlametalWeapons
[Info   :EpicValheimsAdditions.Core] Loaded DeepAbyssWeapons
[Info   :EpicValheimsAdditions.Core] Loaded Vegetation
[Info   :EpicValheimsAdditions.Core] Loaded configs
[Info   :EpicValheimsAdditions.Core] Updated configs
[Info   :   BepInEx] Loading [Precise Piece Placement 1.1.0]
[Info   :   BepInEx] Loading [Gizmo Reloaded 1.1.2]
[Info   :   BepInEx] Loading [MultiCraft 1.0.0]
[Info   :   BepInEx] Loading [MonsterLabZ 2.4.3]
[Info   :   BepInEx] Loading [Monsterzz 0.0.7]
[Info   :   BepInEx] Loading [Speedy Paths Mod 1.0.6]
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Initialized Server Authoritative Config Manager.
[Info   :   BepInEx] Loading [Paddle Power 1.0.1]
[Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.7]
[Info   :   BepInEx] Loading [Blacksmithing 1.1.2]
[Info   :   BepInEx] Loading [Building 1.2.0]
[Info   :   BepInEx] Loading [Cooking 1.1.2]
[Info   :   BepInEx] Loading [Darwin Awards 1.0.2]
[Info   :   BepInEx] Loading [Farming 2.1.0]
[Info   :   BepInEx] Loading [Jewelcrafting 1.0.1]
[Info   :   BepInEx] Loading [Lumberjacking 1.0.1]
[Info   :   BepInEx] Loading [Mining 1.1.1]
[Info   :   BepInEx] Loading [No Skill Drain 1.0.1]
[Info   :   BepInEx] Loading [Professions 1.2.0]
[Info   :   BepInEx] Loading [Ranching 1.0.0]
[Info   :   BepInEx] Loading [Sailing 1.1.2]
[Info   :   BepInEx] Loading [TargetPortal 1.1.3]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.0]
[Info   :   BepInEx] Loading [MethodCallCommand 1.0.0.0]
[Info   :   BepInEx] Loading [Fermenter Percentage 1.0.0]
[Info   :   BepInEx] Loading [Minimal Status Effects 1.0.3]
[Info   :   BepInEx] Loading [ChaosArmor 9.0.7]
[Info   :   BepInEx] Loading [Skyheim 1.1.1]
[Info   :   BepInEx] Loading [Crafting Station Level Range 1.5.0]
[Info   :   BepInEx] Loading [AutoRepair 5.4.1600]
[Info   :   BepInEx] Loading [MonsterMobs 1.1.3]
[Info   :   BepInEx] Loading [jtv 1.1.3]
[Info   :   BepInEx] Loading [jtv_biomes 0.0.1]
[Info   :   BepInEx] Loading [Recipe Customizer 0.0.1]
[Info   :   BepInEx] Loading [Weapon Customizer 0.0.1]
[Info   :   BepInEx] Loading [WendigoMonsterZZ 0.0.7]
[Info   :   BepInEx] Loading [WereBearZZ 0.0.7]
[Info   :   BepInEx] Loading [WhereWolves 0.0.7]
[Info   :   BepInEx] Loading [Wizard 0.0.7]
[Info   :   BepInEx] Loading [YetiMonsterZ 0.0.7]
[Message:   BepInEx] Chainloader startup complete
[Info   :Jotunn.Managers.CommandManager] Adding 1 commands to the Console
[Info   :Jotunn.Managers.InputManager] Registering 10 custom inputs
[Info   :Jotunn.Managers.LocalizationManager] Loading custom localizations
[Info   :Jotunn.Managers.LocalizationManager] Adding tokens for language 'English'
[Warning:RRRMonsters] True
[Info   :   jtv.Jtv] Adding JTV Vegetation
[Info   :   jtv.Jtv] Adding Food
[Warning:Jotunn.Managers.PrefabManager] Failed to clone prefab, can not find base prefab with name: ArmorBarbarianBronzeHelmetJD
[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnVanillaItemsAvailable in AddNewSets.AddArmorSets:
System.NullReferenceException: Object reference not set to an instance of an object
  at Terraheim.Utility.ArmorHelper.AddArmorPiece (System.String setName, System.String location) [0x0015d] in <7bbaa1818a6a412e925b79f46edff69c>:0 
  at Terraheim.Utility.ArmorHelper.AddArmorSet (System.String setName) [0x00001] in <7bbaa1818a6a412e925b79f46edff69c>:0 
  at Terraheim.Armor.AddNewSets.AddArmorSets () [0x00165] in <7bbaa1818a6a412e925b79f46edff69c>:0 
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in <23af5fae305642ad81bdcd4ebd9ef966>:0 
[Info   :Jotunn.Managers.ItemManager] Adding 377 custom items to the ObjectDB
[Warning:RRRMonsters] True
[Info   :Weapon Customizer] Attempting to load weapon data from files...
[Info   :Weapon Customizer] Loaded 0 weapon files.
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Info   :Jotunn.Managers.CommandManager] Adding 1 commands to the Console
[Info   :Jotunn.Managers.PrefabManager] Adding 584 custom prefabs to the ZNetScene
[Info   :Jotunn.Managers.CreatureManager] Adding 3 custom creatures
[Info   :Jotunn.Managers.ItemManager] Adding 377 custom items to the ObjectDB
[Info   :Jotunn.Managers.ItemManager] Adding 214 custom recipes to the ObjectDB
[Info   :Jotunn.Managers.ItemManager] Adding 77 custom status effects to the ObjectDB
[Info   :Jotunn.Managers.ItemManager] Adding 3 custom item conversions
[Warning:RRRMonsters] True
[Info   :Jotunn.Managers.PieceManager] Adding 13 custom pieces to the PieceTables
[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnItemsRegistered in AddNewSets.ModExistingRecipes:
System.NullReferenceException: Object reference not set to an instance of an object
  at Terraheim.Utility.ArmorHelper.AddTieredRecipes (System.String setName, System.Boolean hasHelmet) [0x00152] in <7bbaa1818a6a412e925b79f46edff69c>:0 
  at Terraheim.Armor.AddNewSets.ModExistingRecipes () [0x00125] in <7bbaa1818a6a412e925b79f46edff69c>:0 
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in <23af5fae305642ad81bdcd4ebd9ef966>:0 
[Info   :   jtv.Jtv] Repurposing Crafting Stations
[Info   :Jotunn.Managers.NetworkManager] Registering 2 custom RPCs
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Authoritative Config Registered -> AuthoritativeConfig_nex.SpeedyPaths
[Message:Custom Raids] Writing random events (raids) for specific locations, eg. caves, to file C:\Users\Brandon\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\Debug\default_location_random_events.txt.
[Info   :EpicValheimsAdditions.Core] Loaded Locations
[Info   :EpicValheimsAdditions.Core] Updated EVA Resource drop tables
[Info   :EpicValheimsAdditions.Core] Updated Thors Forge level
[Info   :EpicValheimsAdditions.Core] Updated Alchemystation level
[Info   :jtv_biomes.jtv_biomes] Adding Locations
[Info   :Jotunn.Managers.ZoneManager] Injecting 36 custom locations
[Info   :Jotunn.Managers.ZoneManager] Injecting 4 custom vegetation
[Message:Spawn That!] Successfully general configs.
[Message:Custom Raids] Received package.
[Message:Custom Raids] Successfully unpacked configs.
[Message:Drop That!] Received locations package.
[Message:Drop That!] Successfully received and unpacked locations package.
[Message:Spawn That!] Successfully unpacked local spawner configs.
[Message:Drop That!] Received package.
[Message:Drop That!] Successfully general configs.
[Message:Spawn That!] Successfully unpacked world spawner configs.
[Message:Drop That!] Received package.
[Message:Drop That!] Successfully unpacked CharacterDrop configs.
[Message:Spawn That!] Received locations package.
[Message:Spawn That!] Successfully unpacked locations.
[Message:Drop That!] Received package.
[Message:Drop That!] Successfully unpacked DropTable configs.
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Authoritative Config Registered -> AuthoritativeConfig_nex.SpeedyPaths
[Info   :Jotunn.Managers.SynchronizationManager+<AdminRPC_OnClientReceive>d__30] Received admin status from server: Admin
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Hud.BuffIcon +1: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Hud.BuffIcon +2: 1.39
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Hud.DebuffIcon -1: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Hud.DebuffIcon -2: 0.79
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Performance.Ground Sensor Interval: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Performance.Ground Sensor Radius: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.DirtPathSpeed: 1.15
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.StonePathSpeed: 1.4
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.CultivatedSpeed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.StructureWoodSpeed: 1.15
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.StructureHardWoodSpeed: 1.15
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.StructureStoneSpeed: 1.4
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers.StructureIronSpeed: 1.4
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.DirtPathStamina: 0.8
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.StonePathStamina: 0.7
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.CultivatedStamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.StructureWoodStamina: 0.8
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.StructureHardWoodStamina: 0.8
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.StructureStoneStamina: 0.7
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers.StructureIronStamina: 0.7
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_None_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_None_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_None: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_Meadows_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_Meadows_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_Meadows: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_Swamp_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_Swamp_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_Swamp: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_Mountain_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_Mountain_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_Mountain: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_BlackForest_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_BlackForest_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_BlackForest: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_Plains_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_Plains_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_Plains: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_AshLands_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_AshLands_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_AshLands: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_DeepNorth_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_DeepNorth_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_DeepNorth: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_Ocean_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_Ocean_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_Ocean: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => SpeedModifiers_Biomes.Untamed_Mistlands_Speed: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => StaminaModifiers_Biomes.Untamed_Mistlands_Stamina: 1
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Biome_Mistlands: default
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.PathDirt: Dirt Path
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.PathStone: Stone Path
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.Cultivated: Cultivated
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.StructureWood: Wood
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.StructureHardWood: Hardwood
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.StructureStone: Stone
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied Server Authoritative config pair => Strings.StructureIron: Iron
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Applied 57 config pairs
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Info   :Crafting Station Level Range] $piece_forge (-144540) set to 30 range
[Info   :Crafting Station Level Range] $piece_workbench (-170748) set to 30 range
[Message:MultiCraft] Creating new plus button
[Message:MultiCraft] Creating new minus button
[Message:MultiCraft] CreatingNewAmountText
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Info   :No Skill Drain] no skill drain applied on death
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Info   :AutoRepair] [AutoRepair] Repaired 9 objects!

[Info   :Crafting Station Level Range] $piece_workbench (-170748) set to 40 range
[Info   :AutoRepair] [AutoRepair] Repaired 1 objects!

[Info   :Terraheim.Log] Crafter Name from Add Item Patch<|c|>You<|u|>54d86cee-028b-4805-bf84-df17cdac5406
[Info   :Terraheim.Log] Crafter Name from Add Item Patch<|c|>You<|u|>14730e76-77c3-43d0-a92a-4a2917fd2354<|Blacksmithing.Blacksmithing+SaveSkill, Blacksmithing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|>15
[Info   :Terraheim.Log] Crafter Name from Add Item Patch<|c|>You<|u|>5cb63981-bc41-4bde-873e-3f45ed7347a4<|Blacksmithing.Blacksmithing+SaveSkill, Blacksmithing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|>15
[Info   :Terraheim.Log] Crafter Name from Add Item Patch<|c|>You
[Info   :Terraheim.Log] Crafter Name from Add Item Patch<|c|>You
[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
```

</details>

<details>
<summary>

modlist

</summary>

```
denikson-BepInExPack_Valheim-5.4.1900
mgway-PaddlePower-1.0.2
neurodr0me-RRRCore-2.12.0
neurodr0me-RRRNpcs-0.2.3
neurodr0me-RRRMonsters-2.2.1
thedefside-WeaponCustomizer-0.0.1
thedefside-RecipeCustomizer-0.0.2
OdinPlus-ChickenBoo-2.1.3
ASharpPen-This_Goes_Here-2.1.1
ASharpPen-Spawn_That-1.0.5
ASharpPen-Drop_That-2.3.3
ASharpPen-Custom_Raids-1.6.2
GoldenJude-Judes_Equipment-2.2.0
ValheimModding-Jotunn-2.6.9
DasSauerkraut-Terraheim-2.2.0
Fantu-Sages_Vault-1.1.4
Fantu-PopVillages-1.0.1
Huntardys-EpicValheimsAdditions-1.8.0
GoldenJude-Blacksmiths_tools-2.0.2
AeehyehssReeper-ChaosArmor-9.0.7
MonsterLabZ-MonsterLabZ-2.4.3
thedefside-jtv_biomes-0.0.1
thedefside-Journey_To_Valhalla-1.1.3
Smoothbrain-CreatureLevelAndLootControl-4.4.8
RoundStone-RoundStoneScrollFirstPerson-1.0.0
Tekla-AutoRepair-5.4.1602
Horem-DoOrDieMonsters-0.5.3
DarnHyena-LadyBeardTonic-1.0.2
RandyKnapp-ExtendedItemDataFramework-1.0.7
makail-Skyheim-1.1.1
FixItFelix-NoSkillDrain-1.0.1
Tyrenheim-M3TO_Gizmo_Reloaded-1.1.8
Nextek-SpeedyPaths-1.0.6
Smallo-CraftingStationsLevelBasedBuildRange-1.5.0
LVH-IT-UseEquipmentInWater-0.2.2
LTmadness-FermenterPercentage-1.0.0
AcidWerks-PrecisePlacement-1.1.1
Smoothbrain-Blacksmithing-1.1.2
Smoothbrain-Professions-1.2.0
Smoothbrain-Building-1.2.0
Smoothbrain-Cooking-1.1.2
Smoothbrain-Farming-2.1.0
Smoothbrain-Lumberjacking-1.0.1
Smoothbrain-Mining-1.1.1
Smoothbrain-Ranching-1.0.0
Smoothbrain-Sailing-1.1.2
NotActuallyMine-FloorsAreRoofs-1.0.1
Smoothbrain-Jewelcrafting-1.0.1
Smoothbrain-TargetPortal-1.1.3
Smoothbrain-DarwinAwards-1.0.2
aedenthorn_mods-CraftFromContainers-2.2.2
RandyKnapp-MinimalStatusEffects-1.0.3
MaxiMods-MultiCraft-1.0.0
```

</details>

**Comment by blaxxun-boop** [comment] 2022-06-12 10:45
Isn't there any error message in your log, when this happens? Or is the log you've attached just cut short?

If there is no error message:
Can you open your BepInEx.cfg file from your config folder and add "Info" to the log channels of the Harmony logger? Like this:
```
[Harmony.Logger]

## Specifies which Harmony log channels to listen to.
## NOTE: IL channel dumps the whole patch methods, use only when needed!
# Setting type: LogChannel
# Default value: Warn, Error
# Acceptable values: None, Info, IL, Warn, Error, Debug, All
# Multiple values can be set at the same time by separating them with , (e.g. Debug, Warning)
LogChannels = Warn, Error
```

Then start up the game again and attach the full log of the startup here. That will give us a list of other mods you have, which patch the crafting of items. Feel free to toggle that off afterwards, as it will spam your log quite a bit.

**Comment by blaxxun-boop** [comment] 2022-06-12 15:10
So, apparently, Terraheim breaks, if Jewelcrafting is installed. I will see if there is a small change I could make to change that. If not, I will probably leave it as is, seeing that Terraheim is incredibly outdated and not maintained anymore and buggy as hell for quite some time already. It will break with the next Valheim update anyway and then it's gone.

**Comment by BLovegrove** [comment] 2022-06-12 22:36
Darn, fair enough. Thanks for the heads up!

**Comment by blaxxun-boop** [comment] 2022-06-14 11:36
So, the issue is the [0} in Terraheim here:
https://github.com/DasSauerkraut/Terraheim/blob/master/Patches/CraftingPatch.cs#L25

Would have to be fixed in Terraheim and the author doesn't respond to issues and PRs for over a year now.

Sorry about that, but nothing I can do.

**Closed by blaxxun-boop** 2022-06-14 11:36 UTC
